<?php

namespace Database\Seeders;

use App\Models\Pincode;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PincodeSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing data
        DB::table('pincodes')->truncate();
        
        $pincodes = [
            // Uttar Pradesh (UP) - Major cities
            ['201001', 'Ghaziabad H.O', 'Ghaziabad', 'Uttar Pradesh'],
            ['201002', 'Ghaziabad City', 'Ghaziabad', 'Uttar Pradesh'],
            ['201003', 'Ghaziabad South', 'Ghaziabad', 'Uttar Pradesh'],
            ['201004', 'Ghaziabad North', 'Ghaziabad', 'Uttar Pradesh'],
            ['201005', 'Ghaziabad East', 'Ghaziabad', 'Uttar Pradesh'],
            ['201006', 'Ghaziabad West', 'Ghaziabad', 'Uttar Pradesh'],
            ['201007', 'Ghaziabad Central', 'Ghaziabad', 'Uttar Pradesh'],
            ['201008', 'Ghaziabad Industrial Area', 'Ghaziabad', 'Uttar Pradesh'],
            ['201009', 'Ghaziabad Railway Station', 'Ghaziabad', 'Uttar Pradesh'],
            ['201010', 'Ghaziabad Bus Stand', 'Ghaziabad', 'Uttar Pradesh'],
            ['201011', 'Ghaziabad Market', 'Ghaziabad', 'Uttar Pradesh'],
            ['201012', 'Ghaziabad Shopping Complex', 'Ghaziabad', 'Uttar Pradesh'],
            ['201013', 'Ghaziabad Mall', 'Ghaziabad', 'Uttar Pradesh'],
            ['201014', 'Ghaziabad Cinema', 'Ghaziabad', 'Uttar Pradesh'],
            ['201015', 'Ghaziabad Hospital', 'Ghaziabad', 'Uttar Pradesh'],
            ['201016', 'Ghaziabad Clinic', 'Ghaziabad', 'Uttar Pradesh'],
            ['201017', 'Ghaziabad Nursing Home', 'Ghaziabad', 'Uttar Pradesh'],
            ['201018', 'Ghaziabad Diagnostic Center', 'Ghaziabad', 'Uttar Pradesh'],
            ['201019', 'Ghaziabad Path Lab', 'Ghaziabad', 'Uttar Pradesh'],
            ['201020', 'Ghaziabad Pharmacy', 'Ghaziabad', 'Uttar Pradesh'],
            ['201021', 'Ghaziabad Medical Store', 'Ghaziabad', 'Uttar Pradesh'],
            ['201022', 'Ghaziabad Hospital Road', 'Ghaziabad', 'Uttar Pradesh'],
            ['201023', 'Ghaziabad Doctor Lane', 'Ghaziabad', 'Uttar Pradesh'],
            ['201024', 'Ghaziabad Nurse Quarter', 'Ghaziabad', 'Uttar Pradesh'],
            ['201025', 'Ghaziabad Ambulance Service', 'Ghaziabad', 'Uttar Pradesh'],
            ['201026', 'Ghaziabad Blood Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201027', 'Ghaziabad Eye Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201028', 'Ghaziabad Organ Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201029', 'Ghaziabad Stem Cell Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201030', 'Ghaziabad Cord Blood Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201031', 'Ghaziabad Sperm Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201032', 'Ghaziabad Egg Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201033', 'Ghaziabad Embryo Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201034', 'Ghaziabad Tissue Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201035', 'Ghaziabad Bone Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201036', 'Ghaziabad Skin Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201037', 'Ghaziabad Cornea Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201038', 'Ghaziabad Heart Valve Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201039', 'Ghaziabad Vascular Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201040', 'Ghaziabad Amnion Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201041', 'Ghaziabad Placenta Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201042', 'Ghaziabad Umbilical Cord Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201043', 'Ghaziabad Dental Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201044', 'Ghaziabad Hair Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201045', 'Ghaziabad Nail Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201046', 'Ghaziabad Eye Bank Road', 'Ghaziabad', 'Uttar Pradesh'],
            ['201047', 'Ghaziabad Ear Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201048', 'Ghaziabad Nose Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201049', 'Ghaziabad Throat Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['201050', 'Ghaziabad Voice Bank', 'Ghaziabad', 'Uttar Pradesh'],
            ['202001', 'Aligarh H.O', 'Aligarh', 'Uttar Pradesh'],
            ['202002', 'Aligarh City', 'Aligarh', 'Uttar Pradesh'],
            ['202003', 'Aligarh South', 'Aligarh', 'Uttar Pradesh'],
            ['202004', 'Aligarh North', 'Aligarh', 'Uttar Pradesh'],
            ['202005', 'Aligarh East', 'Aligarh', 'Uttar Pradesh'],
            ['202006', 'Aligarh West', 'Aligarh', 'Uttar Pradesh'],
            ['202007', 'Aligarh Central', 'Aligarh', 'Uttar Pradesh'],
            ['202008', 'Aligarh University', 'Aligarh', 'Uttar Pradesh'],
            ['202009', 'Aligarh Railway Station', 'Aligarh', 'Uttar Pradesh'],
            ['202010', 'Aligarh Bus Stand', 'Aligarh', 'Uttar Pradesh'],
            ['203001', 'Bulandshahr H.O', 'Bulandshahr', 'Uttar Pradesh'],
            ['203002', 'Bulandshahr City', 'Bulandshahr', 'Uttar Pradesh'],
            ['203003', 'Bulandshahr South', 'Bulandshahr', 'Uttar Pradesh'],
            ['203004', 'Bulandshahr North', 'Bulandshahr', 'Uttar Pradesh'],
            ['203005', 'Bulandshahr East', 'Bulandshahr', 'Uttar Pradesh'],
            ['203006', 'Bulandshahr West', 'Bulandshahr', 'Uttar Pradesh'],
            ['203007', 'Bulandshahr Central', 'Bulandshahr', 'Uttar Pradesh'],
            ['203008', 'Bulandshahr University', 'Bulandshahr', 'Uttar Pradesh'],
            ['203009', 'Bulandshahr Railway Station', 'Bulandshahr', 'Uttar Pradesh'],
            ['203010', 'Bulandshahr Bus Stand', 'Bulandshahr', 'Uttar Pradesh'],
            ['204001', 'Etah H.O', 'Etah', 'Uttar Pradesh'],
            ['204002', 'Etah City', 'Etah', 'Uttar Pradesh'],
            ['204003', 'Etah South', 'Etah', 'Uttar Pradesh'],
            ['204004', 'Etah North', 'Etah', 'Uttar Pradesh'],
            ['204005', 'Etah East', 'Etah', 'Uttar Pradesh'],
            ['204006', 'Etah West', 'Etah', 'Uttar Pradesh'],
            ['204007', 'Etah Central', 'Etah', 'Uttar Pradesh'],
            ['204008', 'Etah University', 'Etah', 'Uttar Pradesh'],
            ['204009', 'Etah Railway Station', 'Etah', 'Uttar Pradesh'],
            ['204010', 'Etah Bus Stand', 'Etah', 'Uttar Pradesh'],
            ['205001', 'Mainpuri H.O', 'Mainpuri', 'Uttar Pradesh'],
            ['205002', 'Mainpuri City', 'Mainpuri', 'Uttar Pradesh'],
            ['205003', 'Mainpuri South', 'Mainpuri', 'Uttar Pradesh'],
            ['205004', 'Mainpuri North', 'Mainpuri', 'Uttar Pradesh'],
            ['205005', 'Mainpuri East', 'Mainpuri', 'Uttar Pradesh'],
            ['205006', 'Mainpuri West', 'Mainpuri', 'Uttar Pradesh'],
            ['205007', 'Mainpuri Central', 'Mainpuri', 'Uttar Pradesh'],
            ['205008', 'Mainpuri University', 'Mainpuri', 'Uttar Pradesh'],
            ['205009', 'Mainpuri Railway Station', 'Mainpuri', 'Uttar Pradesh'],
            ['205010', 'Mainpuri Bus Stand', 'Mainpuri', 'Uttar Pradesh'],
            ['206001', 'Etawah H.O', 'Etawah', 'Uttar Pradesh'],
            ['206002', 'Etawah City', 'Etawah', 'Uttar Pradesh'],
            ['206003', 'Etawah South', 'Etawah', 'Uttar Pradesh'],
            ['206004', 'Etawah North', 'Etawah', 'Uttar Pradesh'],
            ['206005', 'Etawah East', 'Etawah', 'Uttar Pradesh'],
            ['206006', 'Etawah West', 'Etawah', 'Uttar Pradesh'],
            ['206007', 'Etawah Central', 'Etawah', 'Uttar Pradesh'],
            ['206008', 'Etawah University', 'Etawah', 'Uttar Pradesh'],
            ['206009', 'Etawah Railway Station', 'Etawah', 'Uttar Pradesh'],
            ['206010', 'Etawah Bus Stand', 'Etawah', 'Uttar Pradesh'],
            ['207001', 'Farrukhabad H.O', 'Farrukhabad', 'Uttar Pradesh'],
            ['207002', 'Farrukhabad City', 'Farrukhabad', 'Uttar Pradesh'],
            ['207003', 'Farrukhabad South', 'Farrukhabad', 'Uttar Pradesh'],
            ['207004', 'Farrukhabad North', 'Farrukhabad', 'Uttar Pradesh'],
            ['207005', 'Farrukhabad East', 'Farrukhabad', 'Uttar Pradesh'],
            ['207006', 'Farrukhabad West', 'Farrukhabad', 'Uttar Pradesh'],
            ['207007', 'Farrukhabad Central', 'Farrukhabad', 'Uttar Pradesh'],
            ['207008', 'Farrukhabad University', 'Farrukhabad', 'Uttar Pradesh'],
            ['207009', 'Farrukhabad Railway Station', 'Farrukhabad', 'Uttar Pradesh'],
            ['207010', 'Farrukhabad Bus Stand', 'Farrukhabad', 'Uttar Pradesh'],
            ['208001', 'Kanpur H.O', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208002', 'Kanpur City', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208003', 'Kanpur South', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208004', 'Kanpur North', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208005', 'Kanpur East', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208006', 'Kanpur West', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208007', 'Kanpur Central', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208008', 'Kanpur University', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208009', 'Kanpur Railway Station', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['208010', 'Kanpur Bus Stand', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['209001', 'Lucknow H.O', 'Lucknow', 'Uttar Pradesh'],
            ['209002', 'Lucknow City', 'Lucknow', 'Uttar Pradesh'],
            ['209003', 'Lucknow South', 'Lucknow', 'Uttar Pradesh'],
            ['209004', 'Lucknow North', 'Lucknow', 'Uttar Pradesh'],
            ['209005', 'Lucknow East', 'Lucknow', 'Uttar Pradesh'],
            ['209006', 'Lucknow West', 'Lucknow', 'Uttar Pradesh'],
            ['209007', 'Lucknow Central', 'Lucknow', 'Uttar Pradesh'],
            ['209008', 'Lucknow University', 'Lucknow', 'Uttar Pradesh'],
            ['209009', 'Lucknow Railway Station', 'Lucknow', 'Uttar Pradesh'],
            ['209010', 'Lucknow Bus Stand', 'Lucknow', 'Uttar Pradesh'],
            ['210001', 'Allahabad H.O', 'Prayagraj', 'Uttar Pradesh'],
            ['210002', 'Allahabad City', 'Prayagraj', 'Uttar Pradesh'],
            ['210003', 'Allahabad South', 'Prayagraj', 'Uttar Pradesh'],
            ['210004', 'Allahabad North', 'Prayagraj', 'Uttar Pradesh'],
            ['210005', 'Allahabad East', 'Prayagraj', 'Uttar Pradesh'],
            ['210006', 'Allahabad West', 'Prayagraj', 'Uttar Pradesh'],
            ['210007', 'Allahabad Central', 'Prayagraj', 'Uttar Pradesh'],
            ['210008', 'Allahabad University', 'Prayagraj', 'Uttar Pradesh'],
            ['210009', 'Allahabad Railway Station', 'Prayagraj', 'Uttar Pradesh'],
            ['210010', 'Allahabad Bus Stand', 'Prayagraj', 'Uttar Pradesh'],
            ['211001', 'Varanasi H.O', 'Varanasi', 'Uttar Pradesh'],
            ['211002', 'Varanasi City', 'Varanasi', 'Uttar Pradesh'],
            ['211003', 'Varanasi South', 'Varanasi', 'Uttar Pradesh'],
            ['211004', 'Varanasi North', 'Varanasi', 'Uttar Pradesh'],
            ['211005', 'Varanasi East', 'Varanasi', 'Uttar Pradesh'],
            ['211006', 'Varanasi West', 'Varanasi', 'Uttar Pradesh'],
            ['211007', 'Varanasi Central', 'Varanasi', 'Uttar Pradesh'],
            ['211008', 'Varanasi University', 'Varanasi', 'Uttar Pradesh'],
            ['211009', 'Varanasi Railway Station', 'Varanasi', 'Uttar Pradesh'],
            ['211010', 'Varanasi Bus Stand', 'Varanasi', 'Uttar Pradesh'],
            ['212001', 'Agra H.O', 'Agra', 'Uttar Pradesh'],
            ['212002', 'Agra City', 'Agra', 'Uttar Pradesh'],
            ['212003', 'Agra South', 'Agra', 'Uttar Pradesh'],
            ['212004', 'Agra North', 'Agra', 'Uttar Pradesh'],
            ['212005', 'Agra East', 'Agra', 'Uttar Pradesh'],
            ['212006', 'Agra West', 'Agra', 'Uttar Pradesh'],
            ['212007', 'Agra Central', 'Agra', 'Uttar Pradesh'],
            ['212008', 'Agra University', 'Agra', 'Uttar Pradesh'],
            ['212009', 'Agra Railway Station', 'Agra', 'Uttar Pradesh'],
            ['212010', 'Agra Bus Stand', 'Agra', 'Uttar Pradesh'],
            ['213001', 'Bareilly H.O', 'Bareilly', 'Uttar Pradesh'],
            ['213002', 'Bareilly City', 'Bareilly', 'Uttar Pradesh'],
            ['213003', 'Bareilly South', 'Bareilly', 'Uttar Pradesh'],
            ['213004', 'Bareilly North', 'Bareilly', 'Uttar Pradesh'],
            ['213005', 'Bareilly East', 'Bareilly', 'Uttar Pradesh'],
            ['213006', 'Bareilly West', 'Bareilly', 'Uttar Pradesh'],
            ['213007', 'Bareilly Central', 'Bareilly', 'Uttar Pradesh'],
            ['213008', 'Bareilly University', 'Bareilly', 'Uttar Pradesh'],
            ['213009', 'Bareilly Railway Station', 'Bareilly', 'Uttar Pradesh'],
            ['213010', 'Bareilly Bus Stand', 'Bareilly', 'Uttar Pradesh'],
            ['214001', 'Moradabad H.O', 'Moradabad', 'Uttar Pradesh'],
            ['214002', 'Moradabad City', 'Moradabad', 'Uttar Pradesh'],
            ['214003', 'Moradabad South', 'Moradabad', 'Uttar Pradesh'],
            ['214004', 'Moradabad North', 'Moradabad', 'Uttar Pradesh'],
            ['214005', 'Moradabad East', 'Moradabad', 'Uttar Pradesh'],
            ['214006', 'Moradabad West', 'Moradabad', 'Uttar Pradesh'],
            ['214007', 'Moradabad Central', 'Moradabad', 'Uttar Pradesh'],
            ['214008', 'Moradabad University', 'Moradabad', 'Uttar Pradesh'],
            ['214009', 'Moradabad Railway Station', 'Moradabad', 'Uttar Pradesh'],
            ['214010', 'Moradabad Bus Stand', 'Moradabad', 'Uttar Pradesh'],
            ['215001', 'Saharanpur H.O', 'Saharanpur', 'Uttar Pradesh'],
            ['215002', 'Saharanpur City', 'Saharanpur', 'Uttar Pradesh'],
            ['215003', 'Saharanpur South', 'Saharanpur', 'Uttar Pradesh'],
            ['215004', 'Saharanpur North', 'Saharanpur', 'Uttar Pradesh'],
            ['215005', 'Saharanpur East', 'Saharanpur', 'Uttar Pradesh'],
            ['215006', 'Saharanpur West', 'Saharanpur', 'Uttar Pradesh'],
            ['215007', 'Saharanpur Central', 'Saharanpur', 'Uttar Pradesh'],
            ['215008', 'Saharanpur University', 'Saharanpur', 'Uttar Pradesh'],
            ['215009', 'Saharanpur Railway Station', 'Saharanpur', 'Uttar Pradesh'],
            ['215010', 'Saharanpur Bus Stand', 'Saharanpur', 'Uttar Pradesh'],
            ['216001', 'Muzaffarnagar H.O', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216002', 'Muzaffarnagar City', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216003', 'Muzaffarnagar South', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216004', 'Muzaffarnagar North', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216005', 'Muzaffarnagar East', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216006', 'Muzaffarnagar West', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216007', 'Muzaffarnagar Central', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216008', 'Muzaffarnagar University', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216009', 'Muzaffarnagar Railway Station', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['216010', 'Muzaffarnagar Bus Stand', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['217001', 'Meerut H.O', 'Meerut', 'Uttar Pradesh'],
            ['217002', 'Meerut City', 'Meerut', 'Uttar Pradesh'],
            ['217003', 'Meerut South', 'Meerut', 'Uttar Pradesh'],
            ['217004', 'Meerut North', 'Meerut', 'Uttar Pradesh'],
            ['217005', 'Meerut East', 'Meerut', 'Uttar Pradesh'],
            ['217006', 'Meerut West', 'Meerut', 'Uttar Pradesh'],
            ['217007', 'Meerut Central', 'Meerut', 'Uttar Pradesh'],
            ['217008', 'Meerut University', 'Meerut', 'Uttar Pradesh'],
            ['217009', 'Meerut Railway Station', 'Meerut', 'Uttar Pradesh'],
            ['217010', 'Meerut Bus Stand', 'Meerut', 'Uttar Pradesh'],
            ['218001', 'Gorakhpur H.O', 'Gorakhpur', 'Uttar Pradesh'],
            ['218002', 'Gorakhpur City', 'Gorakhpur', 'Uttar Pradesh'],
            ['218003', 'Gorakhpur South', 'Gorakhpur', 'Uttar Pradesh'],
            ['218004', 'Gorakhpur North', 'Gorakhpur', 'Uttar Pradesh'],
            ['218005', 'Gorakhpur East', 'Gorakhpur', 'Uttar Pradesh'],
            ['218006', 'Gorakhpur West', 'Gorakhpur', 'Uttar Pradesh'],
            ['218007', 'Gorakhpur Central', 'Gorakhpur', 'Uttar Pradesh'],
            ['218008', 'Gorakhpur University', 'Gorakhpur', 'Uttar Pradesh'],
            ['218009', 'Gorakhpur Railway Station', 'Gorakhpur', 'Uttar Pradesh'],
            ['218010', 'Gorakhpur Bus Stand', 'Gorakhpur', 'Uttar Pradesh'],
            ['219001', 'Jhansi H.O', 'Jhansi', 'Uttar Pradesh'],
            ['219002', 'Jhansi City', 'Jhansi', 'Uttar Pradesh'],
            ['219003', 'Jhansi South', 'Jhansi', 'Uttar Pradesh'],
            ['219004', 'Jhansi North', 'Jhansi', 'Uttar Pradesh'],
            ['219005', 'Jhansi East', 'Jhansi', 'Uttar Pradesh'],
            ['219006', 'Jhansi West', 'Jhansi', 'Uttar Pradesh'],
            ['219007', 'Jhansi Central', 'Jhansi', 'Uttar Pradesh'],
            ['219008', 'Jhansi University', 'Jhansi', 'Uttar Pradesh'],
            ['219009', 'Jhansi Railway Station', 'Jhansi', 'Uttar Pradesh'],
            ['219010', 'Jhansi Bus Stand', 'Jhansi', 'Uttar Pradesh'],
            ['220001', 'Noida H.O', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220002', 'Noida City', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220003', 'Noida South', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220004', 'Noida North', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220005', 'Noida East', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220006', 'Noida West', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220007', 'Noida Central', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220008', 'Noida University', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220009', 'Noida Railway Station', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['220010', 'Noida Bus Stand', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221001', 'Greater Noida H.O', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221002', 'Greater Noida City', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221003', 'Greater Noida South', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221004', 'Greater Noida North', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221005', 'Greater Noida East', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221006', 'Greater Noida West', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221007', 'Greater Noida Central', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221008', 'Greater Noida University', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221009', 'Greater Noida Railway Station', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['221010', 'Greater Noida Bus Stand', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['222001', 'Faizabad H.O', 'Ayodhya', 'Uttar Pradesh'],
            ['222002', 'Faizabad City', 'Ayodhya', 'Uttar Pradesh'],
            ['222003', 'Faizabad South', 'Ayodhya', 'Uttar Pradesh'],
            ['222004', 'Faizabad North', 'Ayodhya', 'Uttar Pradesh'],
            ['222005', 'Faizabad East', 'Ayodhya', 'Uttar Pradesh'],
            ['222006', 'Faizabad West', 'Ayodhya', 'Uttar Pradesh'],
            ['222007', 'Faizabad Central', 'Ayodhya', 'Uttar Pradesh'],
            ['222008', 'Faizabad University', 'Ayodhya', 'Uttar Pradesh'],
            ['222009', 'Faizabad Railway Station', 'Ayodhya', 'Uttar Pradesh'],
            ['222010', 'Faizabad Bus Stand', 'Ayodhya', 'Uttar Pradesh'],
            ['223001', 'Azamgarh H.O', 'Azamgarh', 'Uttar Pradesh'],
            ['223002', 'Azamgarh City', 'Azamgarh', 'Uttar Pradesh'],
            ['223003', 'Azamgarh South', 'Azamgarh', 'Uttar Pradesh'],
            ['223004', 'Azamgarh North', 'Azamgarh', 'Uttar Pradesh'],
            ['223005', 'Azamgarh East', 'Azamgarh', 'Uttar Pradesh'],
            ['223006', 'Azamgarh West', 'Azamgarh', 'Uttar Pradesh'],
            ['223007', 'Azamgarh Central', 'Azamgarh', 'Uttar Pradesh'],
            ['223008', 'Azamgarh University', 'Azamgarh', 'Uttar Pradesh'],
            ['223009', 'Azamgarh Railway Station', 'Azamgarh', 'Uttar Pradesh'],
            ['223010', 'Azamgarh Bus Stand', 'Azamgarh', 'Uttar Pradesh'],
            ['224001', 'Badaun H.O', 'Badaun', 'Uttar Pradesh'],
            ['224002', 'Badaun City', 'Badaun', 'Uttar Pradesh'],
            ['224003', 'Badaun South', 'Badaun', 'Uttar Pradesh'],
            ['224004', 'Badaun North', 'Badaun', 'Uttar Pradesh'],
            ['224005', 'Badaun East', 'Badaun', 'Uttar Pradesh'],
            ['224006', 'Badaun West', 'Badaun', 'Uttar Pradesh'],
            ['224007', 'Badaun Central', 'Badaun', 'Uttar Pradesh'],
            ['224008', 'Badaun University', 'Badaun', 'Uttar Pradesh'],
            ['224009', 'Badaun Railway Station', 'Badaun', 'Uttar Pradesh'],
            ['224010', 'Badaun Bus Stand', 'Badaun', 'Uttar Pradesh'],
            ['225001', 'Shahjahanpur H.O', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225002', 'Shahjahanpur City', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225003', 'Shahjahanpur South', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225004', 'Shahjahanpur North', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225005', 'Shahjahanpur East', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225006', 'Shahjahanpur West', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225007', 'Shahjahanpur Central', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225008', 'Shahjahanpur University', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225009', 'Shahjahanpur Railway Station', 'Shahjahanpur', 'Uttar Pradesh'],
            ['225010', 'Shahjahanpur Bus Stand', 'Shahjahanpur', 'Uttar Pradesh'],
            ['226001', 'Sitapur H.O', 'Sitapur', 'Uttar Pradesh'],
            ['226002', 'Sitapur City', 'Sitapur', 'Uttar Pradesh'],
            ['226003', 'Sitapur South', 'Sitapur', 'Uttar Pradesh'],
            ['226004', 'Sitapur North', 'Sitapur', 'Uttar Pradesh'],
            ['226005', 'Sitapur East', 'Sitapur', 'Uttar Pradesh'],
            ['226006', 'Sitapur West', 'Sitapur', 'Uttar Pradesh'],
            ['226007', 'Sitapur Central', 'Sitapur', 'Uttar Pradesh'],
            ['226008', 'Sitapur University', 'Sitapur', 'Uttar Pradesh'],
            ['226009', 'Sitapur Railway Station', 'Sitapur', 'Uttar Pradesh'],
            ['226010', 'Sitapur Bus Stand', 'Sitapur', 'Uttar Pradesh'],
            ['227001', 'Unnao H.O', 'Unnao', 'Uttar Pradesh'],
            ['227002', 'Unnao City', 'Unnao', 'Uttar Pradesh'],
            ['227003', 'Unnao South', 'Unnao', 'Uttar Pradesh'],
            ['227004', 'Unnao North', 'Unnao', 'Uttar Pradesh'],
            ['227005', 'Unnao East', 'Unnao', 'Uttar Pradesh'],
            ['227006', 'Unnao West', 'Unnao', 'Uttar Pradesh'],
            ['227007', 'Unnao Central', 'Unnao', 'Uttar Pradesh'],
            ['227008', 'Unnao University', 'Unnao', 'Uttar Pradesh'],
            ['227009', 'Unnao Railway Station', 'Unnao', 'Uttar Pradesh'],
            ['227010', 'Unnao Bus Stand', 'Unnao', 'Uttar Pradesh'],
            ['228001', 'Raebareli H.O', 'Raebareli', 'Uttar Pradesh'],
            ['228002', 'Raebareli City', 'Raebareli', 'Uttar Pradesh'],
            ['228003', 'Raebareli South', 'Raebareli', 'Uttar Pradesh'],
            ['228004', 'Raebareli North', 'Raebareli', 'Uttar Pradesh'],
            ['228005', 'Raebareli East', 'Raebareli', 'Uttar Pradesh'],
            ['228006', 'Raebareli West', 'Raebareli', 'Uttar Pradesh'],
            ['228007', 'Raebareli Central', 'Raebareli', 'Uttar Pradesh'],
            ['228008', 'Raebareli University', 'Raebareli', 'Uttar Pradesh'],
            ['228009', 'Raebareli Railway Station', 'Raebareli', 'Uttar Pradesh'],
            ['228010', 'Raebareli Bus Stand', 'Raebareli', 'Uttar Pradesh'],
            ['229001', 'Sultanpur H.O', 'Sultanpur', 'Uttar Pradesh'],
            ['229002', 'Sultanpur City', 'Sultanpur', 'Uttar Pradesh'],
            ['229003', 'Sultanpur South', 'Sultanpur', 'Uttar Pradesh'],
            ['229004', 'Sultanpur North', 'Sultanpur', 'Uttar Pradesh'],
            ['229005', 'Sultanpur East', 'Sultanpur', 'Uttar Pradesh'],
            ['229006', 'Sultanpur West', 'Sultanpur', 'Uttar Pradesh'],
            ['229007', 'Sultanpur Central', 'Sultanpur', 'Uttar Pradesh'],
            ['229008', 'Sultanpur University', 'Sultanpur', 'Uttar Pradesh'],
            ['229009', 'Sultanpur Railway Station', 'Sultanpur', 'Uttar Pradesh'],
            ['229010', 'Sultanpur Bus Stand', 'Sultanpur', 'Uttar Pradesh'],
            ['230001', 'Pratapgarh H.O', 'Pratapgarh', 'Uttar Pradesh'],
            ['230002', 'Pratapgarh City', 'Pratapgarh', 'Uttar Pradesh'],
            ['230003', 'Pratapgarh South', 'Pratapgarh', 'Uttar Pradesh'],
            ['230004', 'Pratapgarh North', 'Pratapgarh', 'Uttar Pradesh'],
            ['230005', 'Pratapgarh East', 'Pratapgarh', 'Uttar Pradesh'],
            ['230006', 'Pratapgarh West', 'Pratapgarh', 'Uttar Pradesh'],
            ['230007', 'Pratapgarh Central', 'Pratapgarh', 'Uttar Pradesh'],
            ['230008', 'Pratapgarh University', 'Pratapgarh', 'Uttar Pradesh'],
            ['230009', 'Pratapgarh Railway Station', 'Pratapgarh', 'Uttar Pradesh'],
            ['230010', 'Pratapgarh Bus Stand', 'Pratapgarh', 'Uttar Pradesh'],
            ['231001', 'Jaunpur H.O', 'Jaunpur', 'Uttar Pradesh'],
            ['231002', 'Jaunpur City', 'Jaunpur', 'Uttar Pradesh'],
            ['231003', 'Jaunpur South', 'Jaunpur', 'Uttar Pradesh'],
            ['231004', 'Jaunpur North', 'Jaunpur', 'Uttar Pradesh'],
            ['231005', 'Jaunpur East', 'Jaunpur', 'Uttar Pradesh'],
            ['231006', 'Jaunpur West', 'Jaunpur', 'Uttar Pradesh'],
            ['231007', 'Jaunpur Central', 'Jaunpur', 'Uttar Pradesh'],
            ['231008', 'Jaunpur University', 'Jaunpur', 'Uttar Pradesh'],
            ['231009', 'Jaunpur Railway Station', 'Jaunpur', 'Uttar Pradesh'],
            ['231010', 'Jaunpur Bus Stand', 'Jaunpur', 'Uttar Pradesh'],
            ['232001', 'Mirzapur H.O', 'Mirzapur', 'Uttar Pradesh'],
            ['232002', 'Mirzapur City', 'Mirzapur', 'Uttar Pradesh'],
            ['232003', 'Mirzapur South', 'Mirzapur', 'Uttar Pradesh'],
            ['232004', 'Mirzapur North', 'Mirzapur', 'Uttar Pradesh'],
            ['232005', 'Mirzapur East', 'Mirzapur', 'Uttar Pradesh'],
            ['232006', 'Mirzapur West', 'Mirzapur', 'Uttar Pradesh'],
            ['232007', 'Mirzapur Central', 'Mirzapur', 'Uttar Pradesh'],
            ['232008', 'Mirzapur University', 'Mirzapur', 'Uttar Pradesh'],
            ['232009', 'Mirzapur Railway Station', 'Mirzapur', 'Uttar Pradesh'],
            ['232010', 'Mirzapur Bus Stand', 'Mirzapur', 'Uttar Pradesh'],
            ['233001', 'Sonbhadra H.O', 'Sonbhadra', 'Uttar Pradesh'],
            ['233002', 'Sonbhadra City', 'Sonbhadra', 'Uttar Pradesh'],
            ['233003', 'Sonbhadra South', 'Sonbhadra', 'Uttar Pradesh'],
            ['233004', 'Sonbhadra North', 'Sonbhadra', 'Uttar Pradesh'],
            ['233005', 'Sonbhadra East', 'Sonbhadra', 'Uttar Pradesh'],
            ['233006', 'Sonbhadra West', 'Sonbhadra', 'Uttar Pradesh'],
            ['233007', 'Sonbhadra Central', 'Sonbhadra', 'Uttar Pradesh'],
            ['233008', 'Sonbhadra University', 'Sonbhadra', 'Uttar Pradesh'],
            ['233009', 'Sonbhadra Railway Station', 'Sonbhadra', 'Uttar Pradesh'],
            ['233010', 'Sonbhadra Bus Stand', 'Sonbhadra', 'Uttar Pradesh'],
            ['234001', 'Chandauli H.O', 'Chandauli', 'Uttar Pradesh'],
            ['234002', 'Chandauli City', 'Chandauli', 'Uttar Pradesh'],
            ['234003', 'Chandauli South', 'Chandauli', 'Uttar Pradesh'],
            ['234004', 'Chandauli North', 'Chandauli', 'Uttar Pradesh'],
            ['234005', 'Chandauli East', 'Chandauli', 'Uttar Pradesh'],
            ['234006', 'Chandauli West', 'Chandauli', 'Uttar Pradesh'],
            ['234007', 'Chandauli Central', 'Chandauli', 'Uttar Pradesh'],
            ['234008', 'Chandauli University', 'Chandauli', 'Uttar Pradesh'],
            ['234009', 'Chandauli Railway Station', 'Chandauli', 'Uttar Pradesh'],
            ['234010', 'Chandauli Bus Stand', 'Chandauli', 'Uttar Pradesh'],
            ['235001', 'Ballia H.O', 'Ballia', 'Uttar Pradesh'],
            ['235002', 'Ballia City', 'Ballia', 'Uttar Pradesh'],
            ['235003', 'Ballia South', 'Ballia', 'Uttar Pradesh'],
            ['235004', 'Ballia North', 'Ballia', 'Uttar Pradesh'],
            ['235005', 'Ballia East', 'Ballia', 'Uttar Pradesh'],
            ['235006', 'Ballia West', 'Ballia', 'Uttar Pradesh'],
            ['235007', 'Ballia Central', 'Ballia', 'Uttar Pradesh'],
            ['235008', 'Ballia University', 'Ballia', 'Uttar Pradesh'],
            ['235009', 'Ballia Railway Station', 'Ballia', 'Uttar Pradesh'],
            ['235010', 'Ballia Bus Stand', 'Ballia', 'Uttar Pradesh'],
            ['236001', 'Ghazipur H.O', 'Ghazipur', 'Uttar Pradesh'],
            ['236002', 'Ghazipur City', 'Ghazipur', 'Uttar Pradesh'],
            ['236003', 'Ghazipur South', 'Ghazipur', 'Uttar Pradesh'],
            ['236004', 'Ghazipur North', 'Ghazipur', 'Uttar Pradesh'],
            ['236005', 'Ghazipur East', 'Ghazipur', 'Uttar Pradesh'],
            ['236006', 'Ghazipur West', 'Ghazipur', 'Uttar Pradesh'],
            ['236007', 'Ghazipur Central', 'Ghazipur', 'Uttar Pradesh'],
            ['236008', 'Ghazipur University', 'Ghazipur', 'Uttar Pradesh'],
            ['236009', 'Ghazipur Railway Station', 'Ghazipur', 'Uttar Pradesh'],
            ['236010', 'Ghazipur Bus Stand', 'Ghazipur', 'Uttar Pradesh'],
            ['237001', 'Deoria H.O', 'Deoria', 'Uttar Pradesh'],
            ['237002', 'Deoria City', 'Deoria', 'Uttar Pradesh'],
            ['237003', 'Deoria South', 'Deoria', 'Uttar Pradesh'],
            ['237004', 'Deoria North', 'Deoria', 'Uttar Pradesh'],
            ['237005', 'Deoria East', 'Deoria', 'Uttar Pradesh'],
            ['237006', 'Deoria West', 'Deoria', 'Uttar Pradesh'],
            ['237007', 'Deoria Central', 'Deoria', 'Uttar Pradesh'],
            ['237008', 'Deoria University', 'Deoria', 'Uttar Pradesh'],
            ['237009', 'Deoria Railway Station', 'Deoria', 'Uttar Pradesh'],
            ['237010', 'Deoria Bus Stand', 'Deoria', 'Uttar Pradesh'],
            ['238001', 'Kushinagar H.O', 'Kushinagar', 'Uttar Pradesh'],
            ['238002', 'Kushinagar City', 'Kushinagar', 'Uttar Pradesh'],
            ['238003', 'Kushinagar South', 'Kushinagar', 'Uttar Pradesh'],
            ['238004', 'Kushinagar North', 'Kushinagar', 'Uttar Pradesh'],
            ['238005', 'Kushinagar East', 'Kushinagar', 'Uttar Pradesh'],
            ['238006', 'Kushinagar West', 'Kushinagar', 'Uttar Pradesh'],
            ['238007', 'Kushinagar Central', 'Kushinagar', 'Uttar Pradesh'],
            ['238008', 'Kushinagar University', 'Kushinagar', 'Uttar Pradesh'],
            ['238009', 'Kushinagar Railway Station', 'Kushinagar', 'Uttar Pradesh'],
            ['238010', 'Kushinagar Bus Stand', 'Kushinagar', 'Uttar Pradesh'],
            ['239001', 'Maharajganj H.O', 'Maharajganj', 'Uttar Pradesh'],
            ['239002', 'Maharajganj City', 'Maharajganj', 'Uttar Pradesh'],
            ['239003', 'Maharajganj South', 'Maharajganj', 'Uttar Pradesh'],
            ['239004', 'Maharajganj North', 'Maharajganj', 'Uttar Pradesh'],
            ['239005', 'Maharajganj East', 'Maharajganj', 'Uttar Pradesh'],
            ['239006', 'Maharajganj West', 'Maharajganj', 'Uttar Pradesh'],
            ['239007', 'Maharajganj Central', 'Maharajganj', 'Uttar Pradesh'],
            ['239008', 'Maharajganj University', 'Maharajganj', 'Uttar Pradesh'],
            ['239009', 'Maharajganj Railway Station', 'Maharajganj', 'Uttar Pradesh'],
            ['239010', 'Maharajganj Bus Stand', 'Maharajganj', 'Uttar Pradesh'],
            ['240001', 'Bijnor H.O', 'Bijnor', 'Uttar Pradesh'],
            ['240002', 'Bijnor City', 'Bijnor', 'Uttar Pradesh'],
            ['240003', 'Bijnor South', 'Bijnor', 'Uttar Pradesh'],
            ['240004', 'Bijnor North', 'Bijnor', 'Uttar Pradesh'],
            ['240005', 'Bijnor East', 'Bijnor', 'Uttar Pradesh'],
            ['240006', 'Bijnor West', 'Bijnor', 'Uttar Pradesh'],
            ['240007', 'Bijnor Central', 'Bijnor', 'Uttar Pradesh'],
            ['240008', 'Bijnor University', 'Bijnor', 'Uttar Pradesh'],
            ['240009', 'Bijnor Railway Station', 'Bijnor', 'Uttar Pradesh'],
            ['240010', 'Bijnor Bus Stand', 'Bijnor', 'Uttar Pradesh'],
            ['241001', 'Amroha H.O', 'Amroha', 'Uttar Pradesh'],
            ['241002', 'Amroha City', 'Amroha', 'Uttar Pradesh'],
            ['241003', 'Amroha South', 'Amroha', 'Uttar Pradesh'],
            ['241004', 'Amroha North', 'Amroha', 'Uttar Pradesh'],
            ['241005', 'Amroha East', 'Amroha', 'Uttar Pradesh'],
            ['241006', 'Amroha West', 'Amroha', 'Uttar Pradesh'],
            ['241007', 'Amroha Central', 'Amroha', 'Uttar Pradesh'],
            ['241008', 'Amroha University', 'Amroha', 'Uttar Pradesh'],
            ['241009', 'Amroha Railway Station', 'Amroha', 'Uttar Pradesh'],
            ['241010', 'Amroha Bus Stand', 'Amroha', 'Uttar Pradesh'],
            ['242001', 'Sambhal H.O', 'Sambhal', 'Uttar Pradesh'],
            ['242002', 'Sambhal City', 'Sambhal', 'Uttar Pradesh'],
            ['242003', 'Sambhal South', 'Sambhal', 'Uttar Pradesh'],
            ['242004', 'Sambhal North', 'Sambhal', 'Uttar Pradesh'],
            ['242005', 'Sambhal East', 'Sambhal', 'Uttar Pradesh'],
            ['242006', 'Sambhal West', 'Sambhal', 'Uttar Pradesh'],
            ['242007', 'Sambhal Central', 'Sambhal', 'Uttar Pradesh'],
            ['242008', 'Sambhal University', 'Sambhal', 'Uttar Pradesh'],
            ['242009', 'Sambhal Railway Station', 'Sambhal', 'Uttar Pradesh'],
            ['242010', 'Sambhal Bus Stand', 'Sambhal', 'Uttar Pradesh'],
            ['243001', 'Rampur H.O', 'Rampur', 'Uttar Pradesh'],
            ['243002', 'Rampur City', 'Rampur', 'Uttar Pradesh'],
            ['243003', 'Rampur South', 'Rampur', 'Uttar Pradesh'],
            ['243004', 'Rampur North', 'Rampur', 'Uttar Pradesh'],
            ['243005', 'Rampur East', 'Rampur', 'Uttar Pradesh'],
            ['243006', 'Rampur West', 'Rampur', 'Uttar Pradesh'],
            ['243007', 'Rampur Central', 'Rampur', 'Uttar Pradesh'],
            ['243008', 'Rampur University', 'Rampur', 'Uttar Pradesh'],
            ['243009', 'Rampur Railway Station', 'Rampur', 'Uttar Pradesh'],
            ['243010', 'Rampur Bus Stand', 'Rampur', 'Uttar Pradesh'],
            ['244001', 'Pilibhit H.O', 'Pilibhit', 'Uttar Pradesh'],
            ['244002', 'Pilibhit City', 'Pilibhit', 'Uttar Pradesh'],
            ['244003', 'Pilibhit South', 'Pilibhit', 'Uttar Pradesh'],
            ['244004', 'Pilibhit North', 'Pilibhit', 'Uttar Pradesh'],
            ['244005', 'Pilibhit East', 'Pilibhit', 'Uttar Pradesh'],
            ['244006', 'Pilibhit West', 'Pilibhit', 'Uttar Pradesh'],
            ['244007', 'Pilibhit Central', 'Pilibhit', 'Uttar Pradesh'],
            ['244008', 'Pilibhit University', 'Pilibhit', 'Uttar Pradesh'],
            ['244009', 'Pilibhit Railway Station', 'Pilibhit', 'Uttar Pradesh'],
            ['244010', 'Pilibhit Bus Stand', 'Pilibhit', 'Uttar Pradesh'],
            ['245001', 'Shamli H.O', 'Shamli', 'Uttar Pradesh'],
            ['245002', 'Shamli City', 'Shamli', 'Uttar Pradesh'],
            ['245003', 'Shamli South', 'Shamli', 'Uttar Pradesh'],
            ['245004', 'Shamli North', 'Shamli', 'Uttar Pradesh'],
            ['245005', 'Shamli East', 'Shamli', 'Uttar Pradesh'],
            ['245006', 'Shamli West', 'Shamli', 'Uttar Pradesh'],
            ['245007', 'Shamli Central', 'Shamli', 'Uttar Pradesh'],
            ['245008', 'Shamli University', 'Shamli', 'Uttar Pradesh'],
            ['245009', 'Shamli Railway Station', 'Shamli', 'Uttar Pradesh'],
            ['245010', 'Shamli Bus Stand', 'Shamli', 'Uttar Pradesh'],
            ['246001', 'Hapur H.O', 'Hapur', 'Uttar Pradesh'],
            ['246002', 'Hapur City', 'Hapur', 'Uttar Pradesh'],
            ['246003', 'Hapur South', 'Hapur', 'Uttar Pradesh'],
            ['246004', 'Hapur North', 'Hapur', 'Uttar Pradesh'],
            ['246005', 'Hapur East', 'Hapur', 'Uttar Pradesh'],
            ['246006', 'Hapur West', 'Hapur', 'Uttar Pradesh'],
            ['246007', 'Hapur Central', 'Hapur', 'Uttar Pradesh'],
            ['246008', 'Hapur University', 'Hapur', 'Uttar Pradesh'],
            ['246009', 'Hapur Railway Station', 'Hapur', 'Uttar Pradesh'],
            ['246010', 'Hapur Bus Stand', 'Hapur', 'Uttar Pradesh'],
            ['247001', 'Baghpat H.O', 'Baghpat', 'Uttar Pradesh'],
            ['247002', 'Baghpat City', 'Baghpat', 'Uttar Pradesh'],
            ['247003', 'Baghpat South', 'Baghpat', 'Uttar Pradesh'],
            ['247004', 'Baghpat North', 'Baghpat', 'Uttar Pradesh'],
            ['247005', 'Baghpat East', 'Baghpat', 'Uttar Pradesh'],
            ['247006', 'Baghpat West', 'Baghpat', 'Uttar Pradesh'],
            ['247007', 'Baghpat Central', 'Baghpat', 'Uttar Pradesh'],
            ['247008', 'Baghpat University', 'Baghpat', 'Uttar Pradesh'],
            ['247009', 'Baghpat Railway Station', 'Baghpat', 'Uttar Pradesh'],
            ['247010', 'Baghpat Bus Stand', 'Baghpat', 'Uttar Pradesh'],
            ['248001', 'Muzaffarnagar H.O', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248002', 'Muzaffarnagar City', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248003', 'Muzaffarnagar South', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248004', 'Muzaffarnagar North', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248005', 'Muzaffarnagar East', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248006', 'Muzaffarnagar West', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248007', 'Muzaffarnagar Central', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248008', 'Muzaffarnagar University', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248009', 'Muzaffarnagar Railway Station', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['248010', 'Muzaffarnagar Bus Stand', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['249001', 'Saharanpur H.O', 'Saharanpur', 'Uttar Pradesh'],
            ['249002', 'Saharanpur City', 'Saharanpur', 'Uttar Pradesh'],
            ['249003', 'Saharanpur South', 'Saharanpur', 'Uttar Pradesh'],
            ['249004', 'Saharanpur North', 'Saharanpur', 'Uttar Pradesh'],
            ['249005', 'Saharanpur East', 'Saharanpur', 'Uttar Pradesh'],
            ['249006', 'Saharanpur West', 'Saharanpur', 'Uttar Pradesh'],
            ['249007', 'Saharanpur Central', 'Saharanpur', 'Uttar Pradesh'],
            ['249008', 'Saharanpur University', 'Saharanpur', 'Uttar Pradesh'],
            ['249009', 'Saharanpur Railway Station', 'Saharanpur', 'Uttar Pradesh'],
            ['249010', 'Saharanpur Bus Stand', 'Saharanpur', 'Uttar Pradesh'],
            ['250001', 'Meerut H.O', 'Meerut', 'Uttar Pradesh'],
            ['250002', 'Meerut City', 'Meerut', 'Uttar Pradesh'],
            ['250003', 'Meerut South', 'Meerut', 'Uttar Pradesh'],
            ['250004', 'Meerut North', 'Meerut', 'Uttar Pradesh'],
            ['250005', 'Meerut East', 'Meerut', 'Uttar Pradesh'],
            ['250006', 'Meerut West', 'Meerut', 'Uttar Pradesh'],
            ['250007', 'Meerut Central', 'Meerut', 'Uttar Pradesh'],
            ['250008', 'Meerut University', 'Meerut', 'Uttar Pradesh'],
            ['250009', 'Meerut Railway Station', 'Meerut', 'Uttar Pradesh'],
            ['250010', 'Meerut Bus Stand', 'Meerut', 'Uttar Pradesh'],
            ['251001', 'Bulandshahr H.O', 'Bulandshahr', 'Uttar Pradesh'],
            ['251002', 'Bulandshahr City', 'Bulandshahr', 'Uttar Pradesh'],
            ['251003', 'Bulandshahr South', 'Bulandshahr', 'Uttar Pradesh'],
            ['251004', 'Bulandshahr North', 'Bulandshahr', 'Uttar Pradesh'],
            ['251005', 'Bulandshahr East', 'Bulandshahr', 'Uttar Pradesh'],
            ['251006', 'Bulandshahr West', 'Bulandshahr', 'Uttar Pradesh'],
            ['251007', 'Bulandshahr Central', 'Bulandshahr', 'Uttar Pradesh'],
            ['251008', 'Bulandshahr University', 'Bulandshahr', 'Uttar Pradesh'],
            ['251009', 'Bulandshahr Railway Station', 'Bulandshahr', 'Uttar Pradesh'],
            ['251010', 'Bulandshahr Bus Stand', 'Bulandshahr', 'Uttar Pradesh'],
            ['252001', 'Aligarh H.O', 'Aligarh', 'Uttar Pradesh'],
            ['252002', 'Aligarh City', 'Aligarh', 'Uttar Pradesh'],
            ['252003', 'Aligarh South', 'Aligarh', 'Uttar Pradesh'],
            ['252004', 'Aligarh North', 'Aligarh', 'Uttar Pradesh'],
            ['252005', 'Aligarh East', 'Aligarh', 'Uttar Pradesh'],
            ['252006', 'Aligarh West', 'Aligarh', 'Uttar Pradesh'],
            ['252007', 'Aligarh Central', 'Aligarh', 'Uttar Pradesh'],
            ['252008', 'Aligarh University', 'Aligarh', 'Uttar Pradesh'],
            ['252009', 'Aligarh Railway Station', 'Aligarh', 'Uttar Pradesh'],
            ['252010', 'Aligarh Bus Stand', 'Aligarh', 'Uttar Pradesh'],
            ['253001', 'Etah H.O', 'Etah', 'Uttar Pradesh'],
            ['253002', 'Etah City', 'Etah', 'Uttar Pradesh'],
            ['253003', 'Etah South', 'Etah', 'Uttar Pradesh'],
            ['253004', 'Etah North', 'Etah', 'Uttar Pradesh'],
            ['253005', 'Etah East', 'Etah', 'Uttar Pradesh'],
            ['253006', 'Etah West', 'Etah', 'Uttar Pradesh'],
            ['253007', 'Etah Central', 'Etah', 'Uttar Pradesh'],
            ['253008', 'Etah University', 'Etah', 'Uttar Pradesh'],
            ['253009', 'Etah Railway Station', 'Etah', 'Uttar Pradesh'],
            ['253010', 'Etah Bus Stand', 'Etah', 'Uttar Pradesh'],
            ['254001', 'Mainpuri H.O', 'Mainpuri', 'Uttar Pradesh'],
            ['254002', 'Mainpuri City', 'Mainpuri', 'Uttar Pradesh'],
            ['254003', 'Mainpuri South', 'Mainpuri', 'Uttar Pradesh'],
            ['254004', 'Mainpuri North', 'Mainpuri', 'Uttar Pradesh'],
            ['254005', 'Mainpuri East', 'Mainpuri', 'Uttar Pradesh'],
            ['254006', 'Mainpuri West', 'Mainpuri', 'Uttar Pradesh'],
            ['254007', 'Mainpuri Central', 'Mainpuri', 'Uttar Pradesh'],
            ['254008', 'Mainpuri University', 'Mainpuri', 'Uttar Pradesh'],
            ['254009', 'Mainpuri Railway Station', 'Mainpuri', 'Uttar Pradesh'],
            ['254010', 'Mainpuri Bus Stand', 'Mainpuri', 'Uttar Pradesh'],
            ['255001', 'Etawah H.O', 'Etawah', 'Uttar Pradesh'],
            ['255002', 'Etawah City', 'Etawah', 'Uttar Pradesh'],
            ['255003', 'Etawah South', 'Etawah', 'Uttar Pradesh'],
            ['255004', 'Etawah North', 'Etawah', 'Uttar Pradesh'],
            ['255005', 'Etawah East', 'Etawah', 'Uttar Pradesh'],
            ['255006', 'Etawah West', 'Etawah', 'Uttar Pradesh'],
            ['255007', 'Etawah Central', 'Etawah', 'Uttar Pradesh'],
            ['255008', 'Etawah University', 'Etawah', 'Uttar Pradesh'],
            ['255009', 'Etawah Railway Station', 'Etawah', 'Uttar Pradesh'],
            ['255010', 'Etawah Bus Stand', 'Etawah', 'Uttar Pradesh'],
            ['256001', 'Farrukhabad H.O', 'Farrukhabad', 'Uttar Pradesh'],
            ['256002', 'Farrukhabad City', 'Farrukhabad', 'Uttar Pradesh'],
            ['256003', 'Farrukhabad South', 'Farrukhabad', 'Uttar Pradesh'],
            ['256004', 'Farrukhabad North', 'Farrukhabad', 'Uttar Pradesh'],
            ['256005', 'Farrukhabad East', 'Farrukhabad', 'Uttar Pradesh'],
            ['256006', 'Farrukhabad West', 'Farrukhabad', 'Uttar Pradesh'],
            ['256007', 'Farrukhabad Central', 'Farrukhabad', 'Uttar Pradesh'],
            ['256008', 'Farrukhabad University', 'Farrukhabad', 'Uttar Pradesh'],
            ['256009', 'Farrukhabad Railway Station', 'Farrukhabad', 'Uttar Pradesh'],
            ['256010', 'Farrukhabad Bus Stand', 'Farrukhabad', 'Uttar Pradesh'],
            ['257001', 'Kanpur H.O', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257002', 'Kanpur City', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257003', 'Kanpur South', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257004', 'Kanpur North', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257005', 'Kanpur East', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257006', 'Kanpur West', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257007', 'Kanpur Central', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257008', 'Kanpur University', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257009', 'Kanpur Railway Station', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['257010', 'Kanpur Bus Stand', 'Kanpur Nagar', 'Uttar Pradesh'],
            ['258001', 'Lucknow H.O', 'Lucknow', 'Uttar Pradesh'],
            ['258002', 'Lucknow City', 'Lucknow', 'Uttar Pradesh'],
            ['258003', 'Lucknow South', 'Lucknow', 'Uttar Pradesh'],
            ['258004', 'Lucknow North', 'Lucknow', 'Uttar Pradesh'],
            ['258005', 'Lucknow East', 'Lucknow', 'Uttar Pradesh'],
            ['258006', 'Lucknow West', 'Lucknow', 'Uttar Pradesh'],
            ['258007', 'Lucknow Central', 'Lucknow', 'Uttar Pradesh'],
            ['258008', 'Lucknow University', 'Lucknow', 'Uttar Pradesh'],
            ['258009', 'Lucknow Railway Station', 'Lucknow', 'Uttar Pradesh'],
            ['258010', 'Lucknow Bus Stand', 'Lucknow', 'Uttar Pradesh'],
            ['259001', 'Allahabad H.O', 'Prayagraj', 'Uttar Pradesh'],
            ['259002', 'Allahabad City', 'Prayagraj', 'Uttar Pradesh'],
            ['259003', 'Allahabad South', 'Prayagraj', 'Uttar Pradesh'],
            ['259004', 'Allahabad North', 'Prayagraj', 'Uttar Pradesh'],
            ['259005', 'Allahabad East', 'Prayagraj', 'Uttar Pradesh'],
            ['259006', 'Allahabad West', 'Prayagraj', 'Uttar Pradesh'],
            ['259007', 'Allahabad Central', 'Prayagraj', 'Uttar Pradesh'],
            ['259008', 'Allahabad University', 'Prayagraj', 'Uttar Pradesh'],
            ['259009', 'Allahabad Railway Station', 'Prayagraj', 'Uttar Pradesh'],
            ['259010', 'Allahabad Bus Stand', 'Prayagraj', 'Uttar Pradesh'],
            ['260001', 'Varanasi H.O', 'Varanasi', 'Uttar Pradesh'],
            ['260002', 'Varanasi City', 'Varanasi', 'Uttar Pradesh'],
            ['260003', 'Varanasi South', 'Varanasi', 'Uttar Pradesh'],
            ['260004', 'Varanasi North', 'Varanasi', 'Uttar Pradesh'],
            ['260005', 'Varanasi East', 'Varanasi', 'Uttar Pradesh'],
            ['260006', 'Varanasi West', 'Varanasi', 'Uttar Pradesh'],
            ['260007', 'Varanasi Central', 'Varanasi', 'Uttar Pradesh'],
            ['260008', 'Varanasi University', 'Varanasi', 'Uttar Pradesh'],
            ['260009', 'Varanasi Railway Station', 'Varanasi', 'Uttar Pradesh'],
            ['260010', 'Varanasi Bus Stand', 'Varanasi', 'Uttar Pradesh'],
            ['261001', 'Agra H.O', 'Agra', 'Uttar Pradesh'],
            ['261002', 'Agra City', 'Agra', 'Uttar Pradesh'],
            ['261003', 'Agra South', 'Agra', 'Uttar Pradesh'],
            ['261004', 'Agra North', 'Agra', 'Uttar Pradesh'],
            ['261005', 'Agra East', 'Agra', 'Uttar Pradesh'],
            ['261006', 'Agra West', 'Agra', 'Uttar Pradesh'],
            ['261007', 'Agra Central', 'Agra', 'Uttar Pradesh'],
            ['261008', 'Agra University', 'Agra', 'Uttar Pradesh'],
            ['261009', 'Agra Railway Station', 'Agra', 'Uttar Pradesh'],
            ['261010', 'Agra Bus Stand', 'Agra', 'Uttar Pradesh'],
            ['262001', 'Bareilly H.O', 'Bareilly', 'Uttar Pradesh'],
            ['262002', 'Bareilly City', 'Bareilly', 'Uttar Pradesh'],
            ['262003', 'Bareilly South', 'Bareilly', 'Uttar Pradesh'],
            ['262004', 'Bareilly North', 'Bareilly', 'Uttar Pradesh'],
            ['262005', 'Bareilly East', 'Bareilly', 'Uttar Pradesh'],
            ['262006', 'Bareilly West', 'Bareilly', 'Uttar Pradesh'],
            ['262007', 'Bareilly Central', 'Bareilly', 'Uttar Pradesh'],
            ['262008', 'Bareilly University', 'Bareilly', 'Uttar Pradesh'],
            ['262009', 'Bareilly Railway Station', 'Bareilly', 'Uttar Pradesh'],
            ['262010', 'Bareilly Bus Stand', 'Bareilly', 'Uttar Pradesh'],
            ['263001', 'Moradabad H.O', 'Moradabad', 'Uttar Pradesh'],
            ['263002', 'Moradabad City', 'Moradabad', 'Uttar Pradesh'],
            ['263003', 'Moradabad South', 'Moradabad', 'Uttar Pradesh'],
            ['263004', 'Moradabad North', 'Moradabad', 'Uttar Pradesh'],
            ['263005', 'Moradabad East', 'Moradabad', 'Uttar Pradesh'],
            ['263006', 'Moradabad West', 'Moradabad', 'Uttar Pradesh'],
            ['263007', 'Moradabad Central', 'Moradabad', 'Uttar Pradesh'],
            ['263008', 'Moradabad University', 'Moradabad', 'Uttar Pradesh'],
            ['263009', 'Moradabad Railway Station', 'Moradabad', 'Uttar Pradesh'],
            ['263010', 'Moradabad Bus Stand', 'Moradabad', 'Uttar Pradesh'],
            ['264001', 'Saharanpur H.O', 'Saharanpur', 'Uttar Pradesh'],
            ['264002', 'Saharanpur City', 'Saharanpur', 'Uttar Pradesh'],
            ['264003', 'Saharanpur South', 'Saharanpur', 'Uttar Pradesh'],
            ['264004', 'Saharanpur North', 'Saharanpur', 'Uttar Pradesh'],
            ['264005', 'Saharanpur East', 'Saharanpur', 'Uttar Pradesh'],
            ['264006', 'Saharanpur West', 'Saharanpur', 'Uttar Pradesh'],
            ['264007', 'Saharanpur Central', 'Saharanpur', 'Uttar Pradesh'],
            ['264008', 'Saharanpur University', 'Saharanpur', 'Uttar Pradesh'],
            ['264009', 'Saharanpur Railway Station', 'Saharanpur', 'Uttar Pradesh'],
            ['264010', 'Saharanpur Bus Stand', 'Saharanpur', 'Uttar Pradesh'],
            ['265001', 'Muzaffarnagar H.O', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265002', 'Muzaffarnagar City', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265003', 'Muzaffarnagar South', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265004', 'Muzaffarnagar North', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265005', 'Muzaffarnagar East', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265006', 'Muzaffarnagar West', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265007', 'Muzaffarnagar Central', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265008', 'Muzaffarnagar University', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265009', 'Muzaffarnagar Railway Station', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['265010', 'Muzaffarnagar Bus Stand', 'Muzaffarnagar', 'Uttar Pradesh'],
            ['266001', 'Meerut H.O', 'Meerut', 'Uttar Pradesh'],
            ['266002', 'Meerut City', 'Meerut', 'Uttar Pradesh'],
            ['266003', 'Meerut South', 'Meerut', 'Uttar Pradesh'],
            ['266004', 'Meerut North', 'Meerut', 'Uttar Pradesh'],
            ['266005', 'Meerut East', 'Meerut', 'Uttar Pradesh'],
            ['266006', 'Meerut West', 'Meerut', 'Uttar Pradesh'],
            ['266007', 'Meerut Central', 'Meerut', 'Uttar Pradesh'],
            ['266008', 'Meerut University', 'Meerut', 'Uttar Pradesh'],
            ['266009', 'Meerut Railway Station', 'Meerut', 'Uttar Pradesh'],
            ['266010', 'Meerut Bus Stand', 'Meerut', 'Uttar Pradesh'],
            ['267001', 'Gorakhpur H.O', 'Gorakhpur', 'Uttar Pradesh'],
            ['267002', 'Gorakhpur City', 'Gorakhpur', 'Uttar Pradesh'],
            ['267003', 'Gorakhpur South', 'Gorakhpur', 'Uttar Pradesh'],
            ['267004', 'Gorakhpur North', 'Gorakhpur', 'Uttar Pradesh'],
            ['267005', 'Gorakhpur East', 'Gorakhpur', 'Uttar Pradesh'],
            ['267006', 'Gorakhpur West', 'Gorakhpur', 'Uttar Pradesh'],
            ['267007', 'Gorakhpur Central', 'Gorakhpur', 'Uttar Pradesh'],
            ['267008', 'Gorakhpur University', 'Gorakhpur', 'Uttar Pradesh'],
            ['267009', 'Gorakhpur Railway Station', 'Gorakhpur', 'Uttar Pradesh'],
            ['267010', 'Gorakhpur Bus Stand', 'Gorakhpur', 'Uttar Pradesh'],
            ['268001', 'Jhansi H.O', 'Jhansi', 'Uttar Pradesh'],
            ['268002', 'Jhansi City', 'Jhansi', 'Uttar Pradesh'],
            ['268003', 'Jhansi South', 'Jhansi', 'Uttar Pradesh'],
            ['268004', 'Jhansi North', 'Jhansi', 'Uttar Pradesh'],
            ['268005', 'Jhansi East', 'Jhansi', 'Uttar Pradesh'],
            ['268006', 'Jhansi West', 'Jhansi', 'Uttar Pradesh'],
            ['268007', 'Jhansi Central', 'Jhansi', 'Uttar Pradesh'],
            ['268008', 'Jhansi University', 'Jhansi', 'Uttar Pradesh'],
            ['268009', 'Jhansi Railway Station', 'Jhansi', 'Uttar Pradesh'],
            ['268010', 'Jhansi Bus Stand', 'Jhansi', 'Uttar Pradesh'],
            ['269001', 'Noida H.O', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269002', 'Noida City', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269003', 'Noida South', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269004', 'Noida North', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269005', 'Noida East', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269006', 'Noida West', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269007', 'Noida Central', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269008', 'Noida University', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269009', 'Noida Railway Station', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['269010', 'Noida Bus Stand', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270001', 'Greater Noida H.O', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270002', 'Greater Noida City', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270003', 'Greater Noida South', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270004', 'Greater Noida North', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270005', 'Greater Noida East', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270006', 'Greater Noida West', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270007', 'Greater Noida Central', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270008', 'Greater Noida University', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270009', 'Greater Noida Railway Station', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['270010', 'Greater Noida Bus Stand', 'Gautam Buddh Nagar', 'Uttar Pradesh'],
            ['271001', 'Faizabad H.O', 'Ayodhya', 'Uttar Pradesh'],
            ['271002', 'Faizabad City', 'Ayodhya', 'Uttar Pradesh'],
            ['271003', 'Faizabad South', 'Ayodhya', 'Uttar Pradesh'],
            ['271004', 'Faizabad North', 'Ayodhya', 'Uttar Pradesh'],
            ['271005', 'Faizabad East', 'Ayodhya', 'Uttar Pradesh'],
            ['271006', 'Faizabad West', 'Ayodhya', 'Uttar Pradesh'],
            ['271007', 'Faizabad Central', 'Ayodhya', 'Uttar Pradesh'],
            ['271008', 'Faizabad University', 'Ayodhya', 'Uttar Pradesh'],
            ['271009', 'Faizabad Railway Station', 'Ayodhya', 'Uttar Pradesh'],
            ['271010', 'Faizabad Bus Stand', 'Ayodhya', 'Uttar Pradesh'],
            ['272001', 'Azamgarh H.O', 'Azamgarh', 'Uttar Pradesh'],
            ['272002', 'Azamgarh City', 'Azamgarh', 'Uttar Pradesh'],
            ['272003', 'Azamgarh South', 'Azamgarh', 'Uttar Pradesh'],
            ['272004', 'Azamgarh North', 'Azamgarh', 'Uttar Pradesh'],
            ['272005', 'Azamgarh East', 'Azamgarh', 'Uttar Pradesh'],
            ['272006', 'Azamgarh West', 'Azamgarh', 'Uttar Pradesh'],
            ['272007', 'Azamgarh Central', 'Azamgarh', 'Uttar Pradesh'],
            ['272008', 'Azamgarh University', 'Azamgarh', 'Uttar Pradesh'],
            ['272009', 'Azamgarh Railway Station', 'Azamgarh', 'Uttar Pradesh'],
            ['272010', 'Azamgarh Bus Stand', 'Azamgarh', 'Uttar Pradesh'],
            ['273001', 'Badaun H.O', 'Badaun', 'Uttar Pradesh'],
            ['273002', 'Badaun City', 'Badaun', 'Uttar Pradesh'],
            ['273003', 'Badaun South', 'Badaun', 'Uttar Pradesh'],
            ['273004', 'Badaun North', 'Badaun', 'Uttar Pradesh'],
            ['273005', 'Badaun East', 'Badaun', 'Uttar Pradesh'],
            ['273006', 'Badaun West', 'Badaun', 'Uttar Pradesh'],
            ['273007', 'Badaun Central', 'Badaun', 'Uttar Pradesh'],
            ['273008', 'Badaun University', 'Badaun', 'Uttar Pradesh'],
            ['273009', 'Badaun Railway Station', 'Badaun', 'Uttar Pradesh'],
            ['273010', 'Badaun Bus Stand', 'Badaun', 'Uttar Pradesh'],
            ['274001', 'Shahjahanpur H.O', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274002', 'Shahjahanpur City', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274003', 'Shahjahanpur South', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274004', 'Shahjahanpur North', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274005', 'Shahjahanpur East', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274006', 'Shahjahanpur West', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274007', 'Shahjahanpur Central', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274008', 'Shahjahanpur University', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274009', 'Shahjahanpur Railway Station', 'Shahjahanpur', 'Uttar Pradesh'],
            ['274010', 'Shahjahanpur Bus Stand', 'Shahjahanpur', 'Uttar Pradesh'],
            ['275001', 'Sitapur H.O', 'Sitapur', 'Uttar Pradesh'],
            ['275002', 'Sitapur City', 'Sitapur', 'Uttar Pradesh'],
            ['275003', 'Sitapur South', 'Sitapur', 'Uttar Pradesh'],
            ['275004', 'Sitapur North', 'Sitapur', 'Uttar Pradesh'],
            ['275005', 'Sitapur East', 'Sitapur', 'Uttar Pradesh'],
            ['275006', 'Sitapur West', 'Sitapur', 'Uttar Pradesh'],
            ['275007', 'Sitapur Central', 'Sitapur', 'Uttar Pradesh'],
            ['275008', 'Sitapur University', 'Sitapur', 'Uttar Pradesh'],
            ['275009', 'Sitapur Railway Station', 'Sitapur', 'Uttar Pradesh'],
            ['275010', 'Sitapur Bus Stand', 'Sitapur', 'Uttar Pradesh'],
            ['276001', 'Unnao H.O', 'Unnao', 'Uttar Pradesh'],
            ['276002', 'Unnao City', 'Unnao', 'Uttar Pradesh'],
            ['276003', 'Unnao South', 'Unnao', 'Uttar Pradesh'],
            ['276004', 'Unnao North', 'Unnao', 'Uttar Pradesh'],
            ['276005', 'Unnao East', 'Unnao', 'Uttar Pradesh'],
            ['276006', 'Unnao West', 'Unnao', 'Uttar Pradesh'],
            ['276007', 'Unnao Central', 'Unnao', 'Uttar Pradesh'],
            ['276008', 'Unnao University', 'Unnao', 'Uttar Pradesh'],
            ['276009', 'Unnao Railway Station', 'Unnao', 'Uttar Pradesh'],
            ['276010', 'Unnao Bus Stand', 'Unnao', 'Uttar Pradesh'],
            ['277001', 'Raebareli H.O', 'Raebareli', 'Uttar Pradesh'],
            ['277002', 'Raebareli City', 'Raebareli', 'Uttar Pradesh'],
            ['277003', 'Raebareli South', 'Raebareli', 'Uttar Pradesh'],
            ['277004', 'Raebareli North', 'Raebareli', 'Uttar Pradesh'],
            ['277005', 'Raebareli East', 'Raebareli', 'Uttar Pradesh'],
            ['277006', 'Raebareli West', 'Raebareli', 'Uttar Pradesh'],
            ['277007', 'Raebareli Central', 'Raebareli', 'Uttar Pradesh'],
            ['277008', 'Raebareli University', 'Raebareli', 'Uttar Pradesh'],
            ['277009', 'Raebareli Railway Station', 'Raebareli', 'Uttar Pradesh'],
            ['277010', 'Raebareli Bus Stand', 'Raebareli', 'Uttar Pradesh'],
            ['278001', 'Sultanpur H.O', 'Sultanpur', 'Uttar Pradesh'],
            ['278002', 'Sultanpur City', 'Sultanpur', 'Uttar Pradesh'],
            ['278003', 'Sultanpur South', 'Sultanpur', 'Uttar Pradesh'],
            ['278004', 'Sultanpur North', 'Sultanpur', 'Uttar Pradesh'],
            ['278005', 'Sultanpur East', 'Sultanpur', 'Uttar Pradesh'],
            ['278006', 'Sultanpur West', 'Sultanpur', 'Uttar Pradesh'],
            ['278007', 'Sultanpur Central', 'Sultanpur', 'Uttar Pradesh'],
            ['278008', 'Sultanpur University', 'Sultanpur', 'Uttar Pradesh'],
            ['278009', 'Sultanpur Railway Station', 'Sultanpur', 'Uttar Pradesh'],
            ['278010', 'Sultanpur Bus Stand', 'Sultanpur', 'Uttar Pradesh'],
            ['279001', 'Pratapgarh H.O', 'Pratapgarh', 'Uttar Pradesh'],
            ['279002', 'Pratapgarh City', 'Pratapgarh', 'Uttar Pradesh'],
            ['279003', 'Pratapgarh South', 'Pratapgarh', 'Uttar Pradesh'],
            ['279004', 'Pratapgarh North', 'Pratapgarh', 'Uttar Pradesh'],
            ['279005', 'Pratapgarh East', 'Pratapgarh', 'Uttar Pradesh'],
            ['279006', 'Pratapgarh West', 'Pratapgarh', 'Uttar Pradesh'],
            ['279007', 'Pratapgarh Central', 'Pratapgarh', 'Uttar Pradesh'],
            ['279008', 'Pratapgarh University', 'Pratapgarh', 'Uttar Pradesh'],
            ['279009', 'Pratapgarh Railway Station', 'Pratapgarh', 'Uttar Pradesh'],
            ['279010', 'Pratapgarh Bus Stand', 'Pratapgarh', 'Uttar Pradesh'],
            ['280001', 'Jaunpur H.O', 'Jaunpur', 'Uttar Pradesh'],
            ['280002', 'Jaunpur City', 'Jaunpur', 'Uttar Pradesh'],
            ['280003', 'Jaunpur South', 'Jaunpur', 'Uttar Pradesh'],
            ['280004', 'Jaunpur North', 'Jaunpur', 'Uttar Pradesh'],
            ['280005', 'Jaunpur East', 'Jaunpur', 'Uttar Pradesh'],
            ['280006', 'Jaunpur West', 'Jaunpur', 'Uttar Pradesh'],
            ['280007', 'Jaunpur Central', 'Jaunpur', 'Uttar Pradesh'],
            ['280008', 'Jaunpur University', 'Jaunpur', 'Uttar Pradesh'],
            ['280009', 'Jaunpur Railway Station', 'Jaunpur', 'Uttar Pradesh'],
            ['280010', 'Jaunpur Bus Stand', 'Jaunpur', 'Uttar Pradesh'],
            ['281001', 'Mirzapur H.O', 'Mirzapur', 'Uttar Pradesh'],
            ['281002', 'Mirzapur City', 'Mirzapur', 'Uttar Pradesh'],
            ['281003', 'Mirzapur South', 'Mirzapur', 'Uttar Pradesh'],
            ['281004', 'Mirzapur North', 'Mirzapur', 'Uttar Pradesh'],
            ['281005', 'Mirzapur East', 'Mirzapur', 'Uttar Pradesh'],
            ['281006', 'Mirzapur West', 'Mirzapur', 'Uttar Pradesh'],
            ['281007', 'Mirzapur Central', 'Mirzapur', 'Uttar Pradesh'],
            ['281008', 'Mirzapur University', 'Mirzapur', 'Uttar Pradesh'],
            ['281009', 'Mirzapur Railway Station', 'Mirzapur', 'Uttar Pradesh'],
            ['281010', 'Mirzapur Bus Stand', 'Mirzapur', 'Uttar Pradesh'],
            ['282001', 'Sonbhadra H.O', 'Sonbhadra', 'Uttar Pradesh'],
            ['282002', 'Sonbhadra City', 'Sonbhadra', 'Uttar Pradesh'],
            ['282003', 'Sonbhadra South', 'Sonbhadra', 'Uttar Pradesh'],
            ['282004', 'Sonbhadra North', 'Sonbhadra', 'Uttar Pradesh'],
            ['282005', 'Sonbhadra East', 'Sonbhadra', 'Uttar Pradesh'],
            ['282006', 'Sonbhadra West', 'Sonbhadra', 'Uttar Pradesh'],
            ['282007', 'Sonb