@extends('layouts.app')

@section('title', 'Spin & Win')

@section('content')
@php
$activeRewards = \App\Models\Reward::where('is_active', true)->get();
$rewardCount = $activeRewards->count();
$segmentAngle = $rewardCount > 0 ? 360 / $rewardCount : 60;
@endphp

<div class="container mx-auto px-4 py-6">
    <div class="max-w-3xl mx-auto">
        <h1 class="text-3xl font-bold text-gray-800 text-center mb-8">Spin & Win Rewards!</h1>

        <!-- Spin Wheel Section -->
        <div class="bg-white rounded-lg shadow-lg p-8 mb-8">
            <div class="text-center">
                @if($canSpin)
                    <div class="mb-6 relative">
                        <!-- Spin Wheel Container -->
                        <div class="relative w-64 h-64 mx-auto">
                            <!-- The Wheel with dynamic segments -->
                            <div id="spinWheel" class="w-full h-full rounded-full relative" 
                                 style="transition: transform 5s cubic-bezier(0.23, 1, 0.32, 1);">
                                <!-- Segments will be generated by JS -->
                            </div>
                            <!-- Pointer -->
                            <div class="absolute -top-2 left-1/2 transform -translate-x-1/2 w-0 h-0 z-20"
                                 style="border-left: 12px solid transparent; border-right: 12px solid transparent; border-top: 20px solid #dc2626;">
                            </div>
                        </div>
                    </div>
                    
                    <p class="text-gray-600 mb-2">Remaining Spins: <span class="font-bold text-indigo-600" id="remainingSpins">{{ $remainingSpins ?? 0 }}</span></p>
                    <p class="text-gray-600 mb-6">You've reached your monthly target! Spin now to win exciting rewards.</p>
                    
                    <button type="button" id="spinButton" onclick="performSpin()" 
                            class="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-bold py-4 px-12 rounded-full text-xl shadow-lg transform transition hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed">
                        SPIN NOW!
                    </button>
                    
                    <!-- CSRF Token for JS -->
                    <meta name="csrf-token" content="{{ csrf_token() }}">
                    
                    <!-- Win Popup Modal -->
                    <div id="winModal" class="fixed inset-0 bg-black bg-opacity-50 hidden items-center justify-center z-50" style="display: none;">
                        <div class="bg-white rounded-lg p-8 max-w-md mx-4 text-center" id="winModalContent" style="transform: scale(0); transition: transform 0.3s ease-out;">
                            <div class="text-6xl mb-4">🎉</div>
                            <h3 class="text-2xl font-bold text-gray-800 mb-2">Congratulations!</h3>
                            <p class="text-gray-600 mb-4">You won:</p>
                            
                            <!-- Reward Image -->
                            <div id="winRewardImageContainer" class="mb-4 hidden">
                                <img id="winRewardImage" src="" alt="Reward" class="h-32 w-32 object-cover rounded-lg mx-auto shadow-lg">
                            </div>
                            
                            <div class="bg-gradient-to-r from-indigo-500 to-purple-600 text-white rounded-lg p-4 mb-6">
                                <p id="winRewardName" class="text-xl font-bold"></p>
                                <p id="winRewardValue" class="text-sm mt-1"></p>
                            </div>
                            <button onclick="closeModal('winModal')" class="bg-gray-600 hover:bg-gray-700 text-white font-semibold py-2 px-6 rounded-lg">
                                Awesome!
                            </button>
                        </div>
                    </div>
                    
                    <!-- Loss Popup Modal -->
                    <div id="lossModal" class="fixed inset-0 bg-black bg-opacity-50 hidden items-center justify-center z-50" style="display: none;">
                        <div class="bg-white rounded-lg p-8 max-w-md mx-4 text-center" id="lossModalContent" style="transform: scale(0); transition: transform 0.3s ease-out;">
                            <div class="text-6xl mb-4">❌</div>
                            <h3 class="text-2xl font-bold text-gray-800 mb-2">Better luck next time!</h3>
                            <p class="text-gray-600 mb-6">Don't give up, try again!</p>
                            <button onclick="closeModal('lossModal')" class="bg-gray-600 hover:bg-gray-700 text-white font-semibold py-2 px-6 rounded-lg">
                                OK
                            </button>
                        </div>
                    </div>
                @else
                    <div class="mb-6">
                        <div class="w-48 h-48 mx-auto bg-gray-200 rounded-full flex items-center justify-center">
                            <span class="text-gray-400 text-6xl">🔒</span>
                        </div>
                    </div>
                    <p class="text-gray-600 mb-4">Complete your monthly target to unlock the spin wheel!</p>
                    <a href="{{ route('doctor.dashboard') }}" class="text-indigo-600 hover:text-indigo-800 font-medium">
                        View Your Progress &rarr;
                    </a>
                @endif
            </div>
        </div>

        <!-- Recent Spins -->
        <div class="bg-white rounded-lg shadow p-6">
            <h2 class="text-xl font-semibold text-gray-800 mb-4">Your Recent Wins</h2>
            
            @if($spinHistory->count() > 0)
                <div class="space-y-3">
                    @foreach($spinHistory as $spin)
                        <div class="flex items-center justify-between p-4 bg-gray-50 rounded-lg">
                            <div class="flex items-center">
                                @if($spin->reward && $spin->reward->image)
                                    <img src="{{ asset('storage/' . $spin->reward->image) }}" alt="{{ $spin->reward->name }}" class="w-10 h-10 rounded-full object-cover mr-3">
                                @else
                                    <div class="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center mr-3">
                                        <span class="text-lg">🎁</span>
                                    </div>
                                @endif
                                <div>
                                    <p class="font-medium text-gray-900">{{ $spin->reward->name }}</p>
                                    <p class="text-sm text-gray-500">{{ $spin->spin_date->format('M d, Y') }}</p>
                                </div>
                            </div>
                            <div>
                                @if($spin->claimed)
                                    <span class="px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm">Claimed</span>
                                @else
                                    <form action="{{ route('doctor.spin.claim', $spin) }}" method="POST" class="inline">
                                        @csrf
                                        <button type="submit" class="px-3 py-1 bg-indigo-600 text-white rounded-full text-sm hover:bg-indigo-700">
                                            Claim
                                        </button>
                                    </form>
                                @endif
                            </div>
                        </div>
                    @endforeach
                </div>
                
                <div class="mt-4 text-center">
                    <a href="{{ route('doctor.spin.history') }}" class="text-indigo-600 hover:text-indigo-800 font-medium">
                        View All History &rarr;
                    </a>
                </div>
            @else
                <p class="text-gray-500 text-center py-8">No spins yet. Complete your target to start winning!</p>
            @endif
        </div>
    </div>
</div>

@if($canSpin)
<script>
// Active rewards from backend
const activeRewards = @json($activeRewards);
const rewardCount = activeRewards.length;
const segmentAngle = 360 / rewardCount;
const colors = ['#6366f1', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981', '#3b82f6', '#ef4444', '#14b8a6'];

let currentRotation = 0;
let isSpinning = false;

// Generate wheel segments on load
function generateWheel() {
    const wheel = document.getElementById('spinWheel');
    let gradientParts = [];
    let labelsHtml = '';
    
    activeRewards.forEach((reward, index) => {
        const startAngle = index * segmentAngle;
        const endAngle = (index + 1) * segmentAngle;
        const color = colors[index % colors.length];
        gradientParts.push(`${color} ${startAngle}deg ${endAngle}deg`);
        
        // Calculate label position (middle of segment)
        const midAngle = startAngle + segmentAngle / 2;
        const rad = (midAngle - 90) * Math.PI / 180;
        const labelRadius = 35; // percentage from center
        const x = 50 + labelRadius * Math.cos(rad);
        const y = 50 + labelRadius * Math.sin(rad);
        
        labelsHtml += `<div class="absolute text-white text-xs font-bold text-center" 
            style="left: ${x}%; top: ${y}%; transform: translate(-50%, -50%); max-width: 60px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
            ${reward.name}
        </div>`;
    });
    
    wheel.style.background = `conic-gradient(${gradientParts.join(', ')})`;
    wheel.style.boxShadow = '0 0 20px rgba(0,0,0,0.2)';
    wheel.innerHTML = `
        <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-12 h-12 bg-white rounded-full shadow-lg flex items-center justify-center z-10">
            <span class="text-2xl">⭐</span>
        </div>
        ${labelsHtml}
    `;
}

// Initialize wheel
generateWheel();

function performSpin() {
    if (isSpinning) return;
    
    const button = document.getElementById('spinButton');
    const wheel = document.getElementById('spinWheel');
    
    isSpinning = true;
    button.disabled = true;
    button.textContent = 'Spinning...';
    
    const csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
    
    fetch('{{ route("doctor.spin.spin") }}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': csrfToken,
            'Accept': 'application/json'
        },
        body: JSON.stringify({})
    })
    .then(response => response.json())
    .then(data => {
        if (!data.success) {
            alert(data.message || 'Spin failed. Please try again.');
            isSpinning = false;
            button.disabled = false;
            button.textContent = 'SPIN NOW!';
            return;
        }
        
        // Find reward index in active rewards
        const rewardIndex = activeRewards.findIndex(r => r.id === data.reward_id);
        const segmentIndex = rewardIndex >= 0 ? rewardIndex : (data.reward_id % rewardCount);
        const targetAngle = segmentIndex * segmentAngle;
        
        // Calculate rotation (5 full spins + position to land on segment)
        const baseRotation = 360 * 5;
        const finalRotation = currentRotation + baseRotation + (360 - targetAngle);
        
        wheel.style.transform = `rotate(${finalRotation}deg)`;
        currentRotation = finalRotation;
        
        setTimeout(() => {
            if (data.is_win) {
                const storageUrl = '{{ asset('storage') }}';
                const imageUrl = data.reward_image ? storageUrl + '/' + data.reward_image : null;
                showWinModal(data.reward_name, data.reward_value, imageUrl);
            } else {
                showLossModal();
            }
            
            const remainingEl = document.getElementById('remainingSpins');
            if (remainingEl) {
                const currentRemaining = parseInt(remainingEl.textContent) || 0;
                if (currentRemaining > 0) {
                    remainingEl.textContent = currentRemaining - 1;
                }
            }
            
            isSpinning = false;
            button.disabled = false;
            button.textContent = 'SPIN AGAIN!';
        }, 5200);
    })
    .catch(error => {
        console.error('Spin error:', error);
        alert('Something went wrong. Please try again.');
        isSpinning = false;
        button.disabled = false;
        button.textContent = 'SPIN NOW!';
    });
}

function showWinModal(name, value, image) {
    document.getElementById('winRewardName').textContent = name || 'Prize';
    document.getElementById('winRewardValue').textContent = value ? '₹' + value : '';
    
    // Handle reward image
    const imageContainer = document.getElementById('winRewardImageContainer');
    const imageEl = document.getElementById('winRewardImage');
    if (image) {
        imageEl.src = image;
        imageContainer.classList.remove('hidden');
    } else {
        imageContainer.classList.add('hidden');
    }
    
    const modal = document.getElementById('winModal');
    const content = document.getElementById('winModalContent');
    
    modal.style.display = 'flex';
    setTimeout(() => content.style.transform = 'scale(1)', 10);
}

function showLossModal() {
    const modal = document.getElementById('lossModal');
    const content = document.getElementById('lossModalContent');
    
    modal.style.display = 'flex';
    setTimeout(() => content.style.transform = 'scale(1)', 10);
}

function closeModal(modalId) {
    const modal = document.getElementById(modalId);
    const content = modal.querySelector('div[id$="ModalContent"]');
    
    content.style.transform = 'scale(0)';
    setTimeout(() => {
        modal.style.display = 'none';
        window.location.reload();
    }, 300);
}
</script>
@endif
@endsection
